### ISSUE TITLE
Contribution/submission default

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/sorting_office#10]
@JeniT has suggested that the default for contribution be "yes". This will need both a code change and appropriate guidance text to avoid duplicate contributions and to ensure that submissions are valid and can be published.

Discuss away.....

**Comment by pezholio** [comment]
Yeah, the only issue with this (as discussed in https://github.com/theodi/shared/issues/509) is if sorting office is used as part of an ETL, we will always end up with two addresses for each submission for that ETL. Also, my thinking was that a specific opt in ensured an informed choice from the user.

**Comment by Floppy** [comment]
The ETLs can opt out easily enough if we swap it round, but I do also think that opt-in is better for informed choice.
