### ISSUE TITLE
"[object Object]" in output when used interactively

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/sorting_office#19]
See screenshot below, don't remember this happening before. 

![screen shot 2015-02-24 at 18 43 19](https://cloud.githubusercontent.com/assets/303693/6356496/a94026b6-bc55-11e4-8bbf-0b882a87d45c.png)

**Comment by pezholio** [comment]
Whoops, I forgot to fix this when I added the URIs

**Comment by giacecco** [comment]
Still not fixed, how is it going?

**Comment by pezholio** [comment]
Forgot to get it merged. Fixes should be on their way!
