### ISSUE TITLE
Parsing successful but no publishing

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/sorting_office#22]
[This list](https://docs.google.com/a/openaddress.es/spreadsheets/d/1KcnqL4XhpkygVSm5vB0JjcWjEreTR8eDESMh-ujkANg/edit#gid=0) (not available to the public) contains a list of problem addresses submitted by our users privately. These are addresses that, for example, are correctly processed by Sorting Office but never get published.

Please check the ingestion / distillation process end to end to understand what is broken. 

If anyone found new addresses that behave like this and want to share, please write to info@openaddressesuk.org if you prefer keeping them confidential.

**Comment by Floppy** [comment]
Great - we have a few more of those as well coming up from the turbot error log.

**Comment by giacecco** [comment]
Current hypothesis is that many of these cases is due to the ingester software wrongly requiring the addresses to have a street. Addresses don't need one to be valid.

**Comment by giacecco** [comment]
I take it back. Address id. 2 in the list is parsed correctly and has a street.
