### ISSUE TITLE
Lost town name

### ISSUE THREAD

**Issue by giacecco** [OpenAddressesUK/sorting_office#24]
See:

```
Rosedale
90 Charles Close
Thornbury
South Gloucestershire
BS35 1LL
```

parsed by Sorting Office into:

```
SAON: Rosedale
PAON: 90
Street: Charles Close
Locality:
Town:
Postcode: BS35 1LL
```

**Comment by Floppy** [comment]
Interesting, I've seen this before as well - thought it was to do with trailing content, but perhaps not.

**Comment by pezholio** [comment]
This is because Thornbury isn't a post town, see https://en.wikipedia.org/wiki/List_of_post_towns_in_the_United_Kingdom. Post towns in BS are Axbridge, Banwell, Bristol, Cheddar, Clevedon, Wedmore, Weston-super-Mare and Winscombe

**Comment by giacecco** [comment]
You're right, the town should be Bristol in this case. This means that the original address is "incomplete". And, because we can't with certainty add a town name to an address from a locality name (yet), we need to drop the address as incomplete.

**Comment by giacecco** [comment]
@pezholio I've updated the test file but can't merge at https://github.com/OpenAddressesUK/sorting_office/pull/28 : there's always "Coverage pending from Coveralls.io". Please take this.

**Comment by pezholio** [comment]
You'll be OK to merge that. Think Coveralls is being a bit slow this morning

**Comment by pezholio** [comment]
Looking at this, the locality should've been picked up, but because https://github.com/OpenAddressesUK/sorting_office/blob/master/lib/sorting_office/models/locality.rb#L5 only picks up the first 10 results. If we widen the scope, it works. 

This may be moot as we don't treat addresses without towns as valid ATM

**Comment by peterkwells** [comment]
Just reopening for a little more discussion for what solution we would _like_ to have:

Some thoughts:
1. In our collaborative maintenance model we are learning about house numbers and streets from users, why not postal towns? We would want low confidence until we have more evidence, but a strict rejection instinctively feels wrong. Thoughts?
2. What makes us think that the Wiki page is right?
3. In this case from Google searching it looks like Thornbury is a locality, not a postal town.
   3.1. Is this a case where we would have wanted to have auto-completed the rest if we had an auto-complete API?
   3.2. Are some user needs met with just a locality? ie is:

Rosedale
90 Charles Close
Thornbury
South Gloucestershire
BS35 1LL

an alias for:

Rosedale
90 Charles Close
Thornbury
BRISTOL
South Gloucestershire
BS35 1LL

where both should/could point to the same URL?

**Comment by giacecco** [comment]
Hello,
1. It is a possibility but managing new or unknown towns is an extreme case. Postcodes and towns are the "backbone" of how we parse addresses at the moment. By requiring a match vs our reference tables we make parsing the rest of the address possible, and will enable us in the next future to be more loose on the street names instead, that have a much higher probability to come from new developments etc. and not being matched. So, it's something to consider, but it can't have priority over managing unknown street names.
2. Oddly enough, it's the only open data source available for that to the best of our knowledge. OS publishes a list of localities, but not of towns. We have informal feedback from the geospatial practitioners we work with that the list is reliable (or was at the moment of ingestion).

3.1. Of course yes. People may identify themselves more with the locality than the town the locality belongs to, and may not specify the town name.

3.2. They should be the same URL because they are the same address.

For some more background: I seem to remember that BS7666 standard we loosely follow for the time being for publishing makes localities part of the address only when the locality name is required to make an address unambiguous. Because the town-postcode combinations are so granular in the UK, it is never the case that locality is needed, that is also why Sorting Office drops locality information when town and postcode are available. 

I suggest we close this and move any requirement arising from this conversation to either the [feature requests forum](https://github.com/OpenAddressesUK/forum/labels/feature%20requests) or directly the [roadmap](https://huboard.com/OpenAddressesUK/roadmap/) where they will have a better audience.
