### ISSUE TITLE
address parse - Tulse Hill matched wrong

### ISSUE THREAD

**Issue by pmackay** [OpenAddressesUK/sorting_office#44]
Tried:

```
St Martin's Youth Hall
   High Trees
   Tulse Hill
   London SW2 3PX
```

and got:

```
SAON:
PAON: St Martin's Youth Hall
Street: Tulse Hill
Locality:
Town: London
Postcode: SW2 3PX
```

Tulse Hill should be the locality. Should sorting office be able to pick that up? Would this be considered an incomplete address if there is no street?

**Comment by pezholio** [comment]
Yeah, I think this is because there's also a street called Tulse Hill nearby. My suspicion is, Sorting Office is finding this before High Trees, and then throwing away that part of the address before the locality gets picked up. I'll see if I can fix this

**Comment by pezholio** [comment]
Fixed in https://github.com/OpenAddressesUK/sorting_office/commit/f1eee035387fdedfdccdfce5d3543677cc3a3220

**Comment by pezholio** [comment]
Thanks for the bug report! :+1:
