### ISSUE TITLE
SSL handshake error

### ISSUE THREAD

**Issue by pmackay** [OpenAddressesUK/sorting_office#46]
Just tried `curl --data "address=62 Effra Court, London SW2 1RB" https://sorting-office.openaddressesuk.org/address` and got:

`curl: (35) error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure`

Anything I'm obviously doing wrong?

**Comment by pezholio** [comment]
Hmmm, just tried that my end and I get a response. It may be a big with cURL. Can you try updating?

**Comment by pmackay** [comment]
ok by installing `7.41.0` and using `-k` to avoid http://stackoverflow.com/questions/3160909/how-do-i-deal-with-certificates-using-curl-while-trying-to-access-an-https-url, I was able to get that to work :) Ta.

**Comment by pezholio** [comment]
Cool cool :smile:
