### ISSUE TITLE
PAON issue - Clapham Angling Preservation Society

### ISSUE THREAD

**Issue by pmackay** [OpenAddressesUK/sorting_office#47]
Tried:

```
Clapham Angling Preservation Society
   The School House
   St John's School
   Overton Road
   London SW9 7HH
```

Got:

```
SAON:

PAON: Clapham Angling Preservation Society

Street: Overton Road

Locality:

Town: London

Postcode: SW9 7HH
```

How would first line be matched to the PAON? Where there is no number, could the school be matched in preference to an organisation name? How does it judge?

**Comment by pmackay** [comment]
FYI, I'm pulling these examples from a dataset that has an Organisation column containing org name and address. It may be that more processing should be done initially to remove org names. Although in this case (and others in similar cases) removing the org name would give `The School House` as PAON, which still maybe isnt the best result.

**Comment by pezholio** [comment]
My instinct here is that the organisation name is not part of the address, so you shouldn't be submitting that as part of the address. However, SAONs and PAONs are not an exact science, so there is a little bit of shonkiness here. That said, I think `The School House` is a legit SAON in this case.

**Comment by pmackay** [comment]
But submitting 

```
The School House
   St John's School
   Overton Road
   London SW9 7HH
```

gives:

```


SAON:

PAON: The School House

Street: Overton Road

Locality:

Town: London

Postcode: SW9 7HH

```

where I would think `St John's School` would be the PAON?

**Comment by pezholio** [comment]
Oh wait, sorry, yeah, I missed the St John's School part there. I'll have a look.

**Comment by pezholio** [comment]
Fixed in https://github.com/OpenAddressesUK/sorting_office/commit/82860ff1f01a15eaf5652e4d85ff6be1b4bb7c89
