### ISSUE TITLE
Contibution/submission guidelines

### ISSUE THREAD

**Issue by peterkwells** [OpenAddressesUK/sorting_office#9]
We need to tighten up the text on --contribute to align with the text in the Submission Guidelines on the front page.

Possibly we should have this text mastered on its own so that it can iterate on its own and be included/linked from anywhere that needs it. We are currently planning to add a stronger link to the new take down policy from the frontpage text either Thu or Fri.

--current frontpage text--
We do not want to receive any names in the submission, other than any company name that may form part of the address. The Open Addresses data that we publish will be about locations, not about people.

Do not worry about the format of the address. The platform is designed and built to support many different formats.

Please be sure not to violate others' intellectual property or privacy rights with your submission. If you think your Intellectual Property rights are being infringed then please email us describing the data that you believe is affected.

When you submit an address we will capture some additional information: specifically the IP address that you are currently using. This information is used to track submissions and as part of our processes to track provenance and to remove any data that is unlawful. Find out more about our privacy policy.

By submitting an address you are saying that Open Addresses Limited can re-use the address and publish it under an open data licence. You are saying that the publication of the address by Open Addresses Limited or third parties does not and will not infringe any of your legal rights or those of any third party.
----end current frontpage text----

**Comment by peterkwells** [comment]
Gianfranco - can we get this one picked up? I think I raised it in the wrong place but seemed logical behaviour to raise the issue in the repository for the API

**Comment by giacecco** [comment]
Moved to https://github.com/OpenAddressesUK/roadmap/issues/79 , candidate for sprint #42
